### ISSUE TITLE
Names don't completely fade in

### ISSUE THREAD

**Issue by sehmon** [fadelakin/rtn#6]
When scrolling to the bottom of the page, the last few names don't get a chance to completely fade in: 

![http://i.imgur.com/DcTKfcC.png](http://i.imgur.com/DcTKfcC.png)

**Comment by sehmon** [comment]
Issue still exists on iPad in the Chrome inspector

**Comment by fadelakin** [comment]
this is fixed now i believe.

**Comment by aunyks** [comment]
Unable to fix but still working at it

**Comment by fadelakin** [comment]
rip
